# Generated by Django 5.2.1 on 2025-06-23 03:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('part_number', models.CharField(max_length=50, unique=True, verbose_name='构件编号')),
                ('material_type', models.CharField(choices=[('carbon_fiber', '碳纤维'), ('glass_fiber', '玻璃纤维'), ('aramid', '芳纶'), ('hybrid', '混合材料'), ('other', '其他')], max_length=30, verbose_name='材料类型')),
                ('thickness', models.FloatField(verbose_name='厚度(mm)')),
                ('processing_requirements', models.TextField(verbose_name='加工要求')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '复合材料构件',
                'verbose_name_plural': '复合材料构件',
            },
        ),
        migrations.CreateModel(
            name='ProcessParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='参数编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
                ('parameter_type', models.CharField(choices=[('number', '数值型'), ('text', '文本型'), ('boolean', '布尔型'), ('date', '日期型'), ('enum', '枚举型')], max_length=20, verbose_name='参数类型')),
                ('enum_values', models.TextField(blank=True, help_text='枚举类型的可选值，用逗号分隔', null=True, verbose_name='枚举值')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='最小值')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='最大值')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
            ],
            options={
                'verbose_name': '工艺参数',
                'verbose_name_plural': '工艺参数',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('tool_type', models.CharField(max_length=50, verbose_name='刀具类型')),
                ('tool_spec', models.CharField(max_length=100, verbose_name='刀具规格')),
                ('initial_wear_threshold', models.FloatField(verbose_name='初始磨损阈值')),
                ('current_status', models.CharField(choices=[('normal', '正常'), ('warning', '警告'), ('worn', '已磨损'), ('broken', '损坏'), ('maintenance', '维护中')], default='normal', max_length=20, verbose_name='当前状态')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='刀具编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '刀具',
                'verbose_name_plural': '刀具',
            },
        ),
        migrations.CreateModel(
            name='ProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='process_data.processcategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '工艺分类',
                'verbose_name_plural': '工艺分类',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('processing_time', models.DateTimeField(verbose_name='加工时间')),
                ('processing_type', models.CharField(choices=[('drilling', '钻孔'), ('milling', '铣削'), ('cutting', '切割'), ('trimming', '修边'), ('other', '其他')], max_length=20, verbose_name='加工类型')),
                ('task_code', models.CharField(max_length=50, unique=True, verbose_name='任务编码')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('paused', '已暂停'), ('aborted', '已中止')], default='planned', max_length=20, verbose_name='任务状态')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='预计持续时间(分钟)')),
                ('actual_duration', models.IntegerField(blank=True, null=True, verbose_name='实际持续时间(分钟)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('composite_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.compositematerial', verbose_name='复合材料构件')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '加工任务',
                'verbose_name_plural': '加工任务',
                'ordering': ['-processing_time'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('surface_roughness', models.FloatField(verbose_name='表面粗糙度(Ra)')),
                ('dimensional_tolerance', models.FloatField(verbose_name='尺寸公差(mm)')),
                ('defect_type', models.CharField(choices=[('none', '无缺陷'), ('delamination', '分层'), ('fiber_breakage', '纤维断裂'), ('matrix_cracking', '基体开裂'), ('burr', '毛刺'), ('surface_roughness', '表面粗糙度不合格'), ('dimensional', '尺寸超差'), ('other', '其他')], default='none', max_length=30, verbose_name='缺陷类型')),
                ('inspection_time', models.DateTimeField(verbose_name='检测时间')),
                ('images', models.TextField(blank=True, null=True, verbose_name='图像路径')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='检验员')),
                ('processing_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_records', to='process_data.processingtask', verbose_name='加工任务')),
            ],
            options={
                'verbose_name': '加工质量',
                'verbose_name_plural': '加工质量',
            },
        ),
        migrations.CreateModel(
            name='ProcessingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('parameter_value', models.CharField(max_length=100, verbose_name='参数值')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='process_data.processingtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '加工参数',
                'verbose_name_plural': '加工参数',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='process_data.processcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '工艺模板',
                'verbose_name_plural': '工艺模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='数据编码')),
                ('name', models.CharField(max_length=100, verbose_name='数据名称')),
                ('batch_number', models.CharField(max_length=100, verbose_name='批次号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='process_data.processtemplate', verbose_name='工艺模板')),
            ],
            options={
                'verbose_name': '工艺数据',
                'verbose_name_plural': '工艺数据',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sensor_type', models.CharField(choices=[('temperature', '温度'), ('vibration', '振动'), ('force', '力'), ('acoustic', '声学'), ('current', '电流'), ('other', '其他')], max_length=20, verbose_name='传感器类型')),
                ('timestamp', models.DateTimeField(verbose_name='时间戳')),
                ('value', models.FloatField(verbose_name='数值')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('sensor_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='传感器ID')),
                ('processing_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='process_data.processingtask', verbose_name='加工任务')),
            ],
            options={
                'verbose_name': '传感器数据',
                'verbose_name_plural': '传感器数据',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='组名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '加工任务组',
                'verbose_name_plural': '加工任务组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='processingtask',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='process_data.taskgroup', verbose_name='所属任务组'),
        ),
        migrations.CreateModel(
            name='TemplateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.processparameter', verbose_name='工艺参数')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.processtemplate', verbose_name='工艺模板')),
            ],
            options={
                'verbose_name': '模板参数',
                'verbose_name_plural': '模板参数',
                'ordering': ['order'],
                'unique_together': {('template', 'parameter')},
            },
        ),
        migrations.AddField(
            model_name='processtemplate',
            name='parameters',
            field=models.ManyToManyField(through='process_data.TemplateParameter', to='process_data.processparameter', verbose_name='工艺参数'),
        ),
        migrations.AddField(
            model_name='processingtask',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.tool', verbose_name='刀具'),
        ),
        migrations.CreateModel(
            name='ToolWearRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('wear_value', models.FloatField(verbose_name='磨损值')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
                ('measurement_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='测量方法')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='测量位置')),
                ('images', models.TextField(blank=True, null=True, verbose_name='图像路径')),
                ('processing_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_wear_records', to='process_data.processingtask', verbose_name='加工任务')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wear_records', to='process_data.tool', verbose_name='刀具')),
            ],
            options={
                'verbose_name': '刀具磨损记录',
                'verbose_name_plural': '刀具磨损记录',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('value', models.TextField(verbose_name='参数值')),
                ('process_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='process_data.processdata', verbose_name='工艺数据')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.processparameter', verbose_name='工艺参数')),
            ],
            options={
                'verbose_name': '参数值',
                'verbose_name_plural': '参数值',
                'unique_together': {('process_data', 'parameter')},
            },
        ),
    ]
