# Generated by Django 5.2.1 on 2025-06-23 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-upload_time'], 'verbose_name': '传感器数据', 'verbose_name_plural': '传感器数据'},
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='value',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='file_name',
            field=models.CharField(default='legacy_data.txt', max_length=255, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='file_size',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='文件大小(字节)'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='file_url',
            field=models.URLField(default='', max_length=500, verbose_name='文件链接'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间'),
        ),
    ]
