# Generated by Django 5.2.1 on 2025-06-22 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='姓名')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='工号')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='角色')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='processdata',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_data.personnel', verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='processingquality',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_data.personnel', verbose_name='检验员'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_data.personnel', verbose_name='操作员'),
        ),
    ]
