# Generated by Django 5.2.1 on 2025-06-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0002_personnel_alter_processdata_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
    ]
